/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.slt.cursojava.view;

import br.edu.ifsp.slt.cursojava.controller.cliente.BloquearClienteController;
import br.edu.ifsp.slt.cursojava.controller.cliente.CancelarClienteController;
import br.edu.ifsp.slt.cursojava.controller.cliente.ReativarClienteController;
import br.edu.ifsp.slt.cursojava.controller.cliente.SalvarClienteFisicoController;
import br.edu.ifsp.slt.cursojava.controller.cliente.SalvarClienteJuridicoController;
import br.edu.ifsp.slt.cursojava.controller.cliente.VisualizarClienteController;
import br.edu.ifsp.slt.cursojava.model.entidades.UnidadeFederativa;
import br.edu.ifsp.slt.cursojava.model.entidades.PreenchimentoObrigatorioException;
import br.edu.ifsp.slt.cursojava.model.entidades.EstadoCliente;
import br.edu.ifsp.slt.cursojava.model.entidades.ClienteFisico;
import br.edu.ifsp.slt.cursojava.model.entidades.ClienteJuridico;
import br.edu.ifsp.slt.cursojava.model.business.ClienteBusiness;
import br.edu.ifsp.slt.cursojava.model.entidades.Cliente;
import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Guilherme
 */
public class ClienteView extends javax.swing.JInternalFrame {

    private ClienteBusiness clienteBusiness;
    private Cliente cliente = null;

    /**
     * Creates new form ClienteView
     *
     * @param clienteBusiness
     * @param cliente
     */
    public ClienteView(ClienteBusiness clienteBusiness, Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        this.clienteBusiness = clienteBusiness;
        DefaultComboBoxModel cmbModel = new DefaultComboBoxModel(UnidadeFederativa.values());
        cmbEstado.setModel(cmbModel);
        try {
            MaskFormatter mascaraTelefone = new MaskFormatter("(##) #####-####");
            mascaraTelefone.install(txtTelefone);
            MaskFormatter mascaraCEP = new MaskFormatter("#####-###");
            mascaraCEP.install(txtCep);
            if (this.cliente instanceof ClienteFisico) {
                MaskFormatter mascaraCpf = new MaskFormatter("###.###.###-##");
                mascaraCpf.install(txtDocumento);
            }
            if (this.cliente instanceof ClienteJuridico) {
                MaskFormatter mascaraCnpj = new MaskFormatter("##.###.###/####-##");
                mascaraCnpj.install(txtDocumento);
            }
        } catch (ParseException ex) {
            Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        lblEstadoCliente = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblDocumento = new javax.swing.JLabel();
        lblSobrenome = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblLogradouro = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        txtEstadoCliente = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        topSeparator = new javax.swing.JSeparator();
        txtNome = new javax.swing.JTextField();
        txtSobrenome = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtLogradouro = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<String>();
        txtEmail = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnBloquear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnReativar = new javax.swing.JButton();
        bottomSeparator = new javax.swing.JSeparator();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCep = new javax.swing.JFormattedTextField();
        txtDocumento = new javax.swing.JFormattedTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Cliente");

        lblCodigo.setText("Código Cliente:");

        lblEstadoCliente.setText("Estado Cliente:");

        lblNome.setText("Nome:");

        lblDocumento.setText("CPF/CNPJ:");

        lblSobrenome.setText("Sobrenome:");

        lblCidade.setText("Cidade:");

        lblLogradouro.setText("Logradouro:");

        lblEmail.setText("E-mail:");

        lblTelefone.setText("Telefone:");

        lblCep.setText("CEP:");

        lblEstado.setText("Estado:");

        txtEstadoCliente.setEditable(false);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnBloquear.setText("Bloquear");
        btnBloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloquearActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnReativar.setText("Reativar");
        btnReativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReativarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBloquear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReativar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEstadoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstadoCliente))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLogradouro)
                            .addComponent(lblSobrenome)
                            .addComponent(lblNome)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCidade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTelefone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDocumento, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail)
                            .addComponent(txtLogradouro)
                            .addComponent(txtSobrenome)
                            .addComponent(txtNome))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtDocumento)))
            .addComponent(topSeparator)
            .addComponent(bottomSeparator)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoCliente)
                    .addComponent(txtEstadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addGap(3, 3, 3)
                .addComponent(topSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSobrenome)
                    .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidade)
                    .addComponent(lblCep)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumento)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(bottomSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnBloquear)
                    .addComponent(btnReativar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparFormulario(JTextField... campos) {
        for (JTextField campo : campos) {
            campo.setText("");
        }
    }

    private void validarPreenchimentoObrigatorio(JTextField... campos) throws PreenchimentoObrigatorioException {
        for (JTextField campo : campos) {
            if (campo.getText() == null || campo.getText().isEmpty()) {
                campo.setBackground(Color.YELLOW);
                throw new PreenchimentoObrigatorioException("Preenchimento obrigatório: campo em amarelo não pode estar em branco!");
            } else {
                campo.setBackground(Color.WHITE);
            }
        }
    }

    public static boolean isNumero(String string) {
        try {
            Integer.parseInt(string);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            if (this.cliente instanceof ClienteFisico) {
                validarPreenchimentoObrigatorio(txtNome, txtSobrenome, txtCidade);
                if (txtCodigoCliente.getText() != null && txtCodigoCliente.getText().length() != 0) {
                    if (!isNumero(txtCodigoCliente.getText())) {
                        JOptionPane.showMessageDialog(this, "Campo código precisa ser númerico!");
                        return;
                    }
                    SalvarClienteFisicoController salvarClienteFisico = new SalvarClienteFisicoController(clienteBusiness);
                    String mensagemSucesso = salvarClienteFisico.executar(txtCodigoCliente.getText(), txtNome.getText(), txtSobrenome.getText(),
                            txtLogradouro.getText(), txtCidade.getText(), (UnidadeFederativa) cmbEstado.getSelectedItem(), txtTelefone.getText(),
                            txtEmail.getText(), EstadoCliente.ATIVO, txtDocumento.getText());
                    JOptionPane.showMessageDialog(null, mensagemSucesso);
                } else {
                    return;
                }
                this.limparFormulario(txtCodigoCliente, txtNome, txtSobrenome, txtLogradouro, txtCidade,
                        txtTelefone, txtEmail, txtDocumento);
            }

            if (this.cliente instanceof ClienteJuridico) {
                validarPreenchimentoObrigatorio(txtNome, txtCidade, txtCidade);
                if (txtCodigoCliente.getText() != null && txtCodigoCliente.getText().length() != 0) {
                    if (!isNumero(txtCodigoCliente.getText())) {
                        JOptionPane.showMessageDialog(this, "Campo código precisa ser númerico!");
                        return;
                    }
                    SalvarClienteJuridicoController salvarClienteJuridico = new SalvarClienteJuridicoController(clienteBusiness);
                    String mensagemSucesso = salvarClienteJuridico.executar(txtCodigoCliente.getText(), txtNome.getText(), txtSobrenome.getText(),
                            txtLogradouro.getText(), txtCidade.getText(), (UnidadeFederativa) cmbEstado.getSelectedItem(), txtTelefone.getText(),
                            txtEmail.getText(), EstadoCliente.ATIVO, txtDocumento.getText());
                    JOptionPane.showMessageDialog(null, mensagemSucesso);
                } else {
                    return;
                }
                this.limparFormulario(txtCodigoCliente, txtNome, txtSobrenome, txtLogradouro, txtCidade,
                        txtTelefone, txtEmail, txtDocumento);
            }
        } catch (PreenchimentoObrigatorioException ex) {
            JOptionPane.showMessageDialog(null, ex.getMensagem());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed


    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (txtCodigoCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, digite o código do cliente!");
            return;
        }

        if (!isNumero(txtCodigoCliente.getText())) {
            JOptionPane.showMessageDialog(this, "Por favor, digite um número no código do cliente!");
            return;
        }

        VisualizarClienteController visualizarClienteController = new VisualizarClienteController(clienteBusiness);
        this.cliente = visualizarClienteController.executar(Integer.parseInt(txtCodigoCliente.getText()));
        if (this.cliente == null) {
            JOptionPane.showMessageDialog(this, "Cliente não encontrado!");
        } else {
            JOptionPane.showMessageDialog(this, this.cliente);
        }
        this.txtCodigoCliente.setText(Integer.toString(this.cliente.getCodigo()));
        this.txtEstadoCliente.setText(this.cliente.getEstadoCliente().toString());
        this.txtNome.setText(this.cliente.getNome());
        this.txtSobrenome.setText(this.cliente.getSobrenome());
        this.txtLogradouro.setText(this.cliente.getEndereco().getLogradouro());
        this.txtCidade.setText(this.cliente.getEndereco().getLogradouro());
        this.cmbEstado.setSelectedItem(this.cliente.getEndereco().getUF());
        this.txtTelefone.setText(this.cliente.getTelefone());
        this.txtEmail.setText(this.cliente.getEmail());
        this.txtDocumento.setText(this.cliente.getDocumento());
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnBloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloquearActionPerformed
        BloquearClienteController bloquearClienteController = new BloquearClienteController(clienteBusiness);
        String mensagem = bloquearClienteController.executar(Integer.parseInt(txtCodigoCliente.getText()));
        JOptionPane.showMessageDialog(this, mensagem);
        this.limparFormulario(txtCodigoCliente, txtNome, txtSobrenome, txtLogradouro, txtCidade,
                txtTelefone, txtEmail, txtDocumento);
    }//GEN-LAST:event_btnBloquearActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        CancelarClienteController cancelarClienteController = new CancelarClienteController(clienteBusiness);
        String mensagem = cancelarClienteController.executar(Integer.parseInt(txtCodigoCliente.getText()));
        JOptionPane.showMessageDialog(this, mensagem);
        this.limparFormulario(txtCodigoCliente, txtNome, txtSobrenome, txtLogradouro, txtCidade,
                txtTelefone, txtEmail, txtDocumento);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnReativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReativarActionPerformed
        ReativarClienteController reativarClienteController = new ReativarClienteController(clienteBusiness);
        String mensagem = reativarClienteController.executar(Integer.parseInt(txtCodigoCliente.getText()));
        JOptionPane.showMessageDialog(this, mensagem);
        this.limparFormulario(txtCodigoCliente, txtNome, txtSobrenome, txtLogradouro, txtCidade,
                txtTelefone, txtEmail, txtDocumento);
    }//GEN-LAST:event_btnReativarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ClienteView().setVisible(true);
            }
        });
    }

    public void preencherCampos() {
        this.txtCodigoCliente.setText(String.valueOf(this.cliente.getCodigo()));
        this.txtNome.setText(this.cliente.getNome());
        this.txtSobrenome.setText(this.cliente.getSobrenome());
        this.txtLogradouro.setText(this.cliente.getEndereco().getLogradouro());
        this.txtCidade.setText(this.cliente.getEndereco().getCidade());
        this.txtTelefone.setText(this.cliente.getTelefone());
        this.txtEmail.setText(this.cliente.getEmail());
        this.txtDocumento.setText(this.cliente.getDocumento());
        this.txtEstadoCliente.setText(this.cliente.getEstadoCliente().toString());
        this.cmbEstado.setSelectedItem(this.cliente.getEndereco().getUF());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator bottomSeparator;
    public javax.swing.JButton btnBloquear;
    public javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnReativar;
    public javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigo;
    public javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoCliente;
    private javax.swing.JLabel lblLogradouro;
    public javax.swing.JLabel lblNome;
    public javax.swing.JLabel lblSobrenome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JSeparator topSeparator;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigoCliente;
    public javax.swing.JFormattedTextField txtDocumento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstadoCliente;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNome;
    public javax.swing.JTextField txtSobrenome;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
